
find_package(FLTK NO_MODULE)
if(NOT FLTK_FOUND)
  set(_CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH})
  unset(CMAKE_MODULE_PATH)
  include(FindFLTK)
  set(CMAKE_MODULE_PATH ${_CMAKE_MODULE_PATH})
  unset(_CMAKE_MODULE_PATH)
endif()

if(NOT FLTK_INCLUDE_DIRS)
  set(FLTK_INCLUDE_DIRS ${FLTK_INCLUDE_DIR})
endif()
if (TARGET fltk_gl_STATIC)
  set(FLTK_LIBRARY fltk_gl_STATIC)
elseif (TARGET fltk_gl_SHARED)
  set(FLTK_LIBRARY fltk_gl_SHARED)
elseif (TARGET fltk_gl)
  set(FLTK_LIBRARY fltk_gl)
endif ()
if(NOT FLTK_LIBRARIES)
  set(FLTK_LIBRARIES ${FLTK_LIBRARY})
endif()
