
find_package(FLTK NO_MODULE)

message("FLTK_INCLUDE_DIR: ${FLTK_INCLUDE_DIR}")
message("FLTK_INCLUDE_DIRS: ${FLTK_INCLUDE_DIRS}")
message("FLTK_LIBRARIES: ${FLTK_LIBRARIES}")
message("FLTK_LIBRARIES: ${FLTK_LIBRARIES}")
